TESTDIR=../../test/parserverilog
s:
	cd $(TESTDIR); make s
d:
	cd $(TESTDIR); make d
p:
	cd $(TESTDIR); make p
rs:
	cd $(TESTDIR); make rs
r:
	cd $(TESTDIR); make r
clean:
	cd $(TESTDIR); make clean

